version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      k8s:
        patterns:
          - k8s.io/api*
          - k8s.io/client-go
          - sigs.k8s.io/controller-runtime
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      day: "monday"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      day: "monday"
    open-pull-requests-limit: 5
