apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elector.fullname" . }}
  labels:
    {{- include "elector.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/match: "true"
data:
  elector_image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
